### ISSUE TITLE
Add support for external secrets

### ISSUE THREAD

**Issue by s4ke** [neuroforgede/docker-stack-deploy#11]
Right now we crash if secrets don't specify a file. For external secrets such as globally defined certificates in a cluster this would cause crashes when deploying.

**Comment by YuryHrytsuk** [comment]
When I see the title of this PR and the `Closed` status, I think that this is implemented. 

While in fact, this is not implemented but ignored (with a warning log).

A bit confusing

**Comment by s4ke** [comment]
This is in fact implemented as the behaviour in the commit is the best we came up with so far. If a secret is external, it is not controlled by the stack so computing the hashes would be quite hard.

What behaviour would you expect?
