### ISSUE TITLE
Enable custom docker binary location

### ISSUE THREAD

**Issue by dbrw** [neuroforgede/docker-stack-deploy#12]
Hi, just around this week I try to use docker-sdp on Nixos. Because of the way Nixos build  the docker binary location is not in `/usr/bin/docker`, neither in `/bin/docker` like expected in https://github.com/neuroforgede/docker-stack-deploy/blob/3327753b69bf63917cc1c68c78750522f9db335a/docker_stack_deploy/cli/deployer.py#L277C9-L277C9.

I think custom docker binary location might be set via ENV variable or config file.

**Comment by s4ke** [comment]
I agree that this is a topic that we should address, maybe just use whatever is on the PATH?

Want to create a PR?

**Comment by dbrw** [comment]
I'll create a PR for this.

edit:
created #13
